### ISSUE TITLE
Mobs in paw hit for 700+

### ISSUE THREAD

**Issue by TheGrandPackard** [xackery/legacyofcain#31]
Infected paw mobs are still hitting well over 700 scaling this down would be an idea zone for 60+ to level

**Comment by xackery** [comment]
https://github.com/xackery/legacyofcain/blob/master/zone/npc.cpp#L2254
the logic used for 60+ probably is overtuned with this:
```cpp
if (GetLevel() >= 66) {
		if (min_dmg==0)
			min_dmg = 220;
		if (max_dmg==0)
			max_dmg = ((((99000)*(GetLevel()-64))/400)*AC_adjust/10);
	}
```
likely just adjust that

**Comment by xackery** [comment]
if all other levels are ok, that is

**Comment by mjbcb0717** [comment]
I ran around in DN and hateb they seemed fine after patch unless it was a champ they where still hitting around 450s but I guess they should be harder anyways.
