### ISSUE TITLE
Epics/det's/others

### ISSUE THREAD

**Issue by mjbcb0717** [xackery/legacyofcain#33]
Epics can still be clicked from inventory by all classes, only mage can actually be equipped rest say class:none

Detrimentals such as rabies or diseases with timers 15+ minutes should be removed or last only a few minutes. Death touch removed. 

Starting players need some kinda wep I gave out a bunch past few days to get people on their feet. 

Access to the #scribe command for spells and spell components removed for now.

**Comment by xackery** [comment]
cleric epic - must be equipped i tried to click it

**Comment by xackery** [comment]
Magician epic same thing.. which epics?

**Comment by TheGrandPackard** [comment]
Starting weapons have been implemented, tested, and deployed as of 2 days ago.

**Comment by TheGrandPackard** [comment]
Spells now auto-scribe on level up, so there is no need to have the #scribe command.

**Comment by xackery** [comment]
let's split issues apart instead of clumping them together. 
* Verify epics can't be clicked - #34
* remove detrimentals like rabies or diseases with longer timers (or lower duration) - #35
* remove DT - #36
* starting players do get weaps now.

**Comment by TheGrandPackard** [comment]
#32 handles spell reagents

**Comment by mjbcb0717** [comment]
Epics was clickable last night before I went to bed must of been handled sometime after gotca!

**Comment by xackery** [comment]
specify which epics, please, there's many epics and they all have different ways they're handled, I did a quick check of magician and cleric, and they aren't

**Comment by mjbcb0717** [comment]
Was mage cleric and druid. I have not been on yet to check again.
